### PR TITLE
Updates test case value

### PR DESCRIPTION
**Pull request by ulgens**
I cherry-picked the commit from `bare_except` branch.

### CODE REVIEW

**Comment by ulgens** [comment]
This branch passed the test but master failed. I don't know why Travis checks two branches.

**Comment by ferittuncer** [comment]
It checks this branch and pull request. It means if you merge this it will fail.

**Comment by ferittuncer** [comment]
I see parallel requests not permitted message in the logs.

**Comment by ulgens** [comment]
@ferittuncer I changed concurrent build setting on Travis, just sent a mail about it. Restarting the build now, should be okay in a minute.

**Comment by ferittuncer** [comment]
We should configure Travis to run again after failing. Server sometimes fails even if the change is not breaking tests.

**Pull request merged**
