### PR TITLE
Don't use bare except, let things crash

### PR DESCRIPTION
**Pull request by ulgens**
We don't handle any of this exceptions manually. Bare excepts just hides the error. It's better to let it crash with original error message and stacktrace.

### CODE REVIEW

**Comment by ferittuncer** [comment]
Tests fail because of missing `pipeline_token` environment variable strangely. I'll investigate it.

**Comment by ferittuncer** [comment]
Can you see the logs by the way? If not I can give permission.

**Comment by ferittuncer** [comment]
`pipeline_token` env. var. looks like intact. I'll check whether ITU cancelled my authorization. (It's been some time since I got my auth.)

**Comment by ferittuncer** [comment]
Looks like those `except raise` blocks was necessary. 

As we run `nosetests` process and we don't want `nosetests` to exit if an exception occurs unexpectedly. And perhaps without `except raise` block, this is what happens. 

If you have a better idea let's implement the tests that way, otherwise let's keep those `except raise` blocks for now @ulgens

**Comment by ulgens** [comment]
How does the token work fine? Is it still in travis env? If so, why it's not accessible?

I got your point but if an exception occurs unexpectedly during tests, it means tests are broke. It's different than tests are failing and i think it should crash loudly as possible. Also, in travis log, nosetests doesn't exit after the first one fails. Alll 5 tests called and run successfully and they all crashed independently. I'm getting same result (with cleaner output) with master branch on my local, where is no `pipeline_token` defined.

**Comment by ferittuncer** [comment]
My token still authenticates calls. I confirmed it by calling the API manually.

Also, token is still intact in Travis environment, confirmed. 

Problem is, with this commit, nosetests started to mask real tests outputs and  instead it says KeyError no matter what. You can verify this by comparing to last commits build. You will see that previously it was reporting FAIL with assertion errors which is correct, now it is reporting ERROR with KeyError which is unexpected. 

So to my understanding, deleting raise excepts broke test suite. Perhaps we can find a harmless way to clean bare excepts, that would be much better. Otherwise the test suite will output useless logs, KeyError no matter what.

Perhaps we can find something about this in nosetest docs.

**Comment by ulgens** [comment]
Got it, thanks. I should try it with a valid token on my local first, then i'll send the fix.

**Comment by ferittuncer** [comment]
Did you apply for a token yet?

**Comment by ulgens** [comment]
I did, waiting for response now.

**Comment by ferittuncer** [comment]
Any updates on this? @ulgens

**Comment by ulgens** [comment]
I couldn't get any response for token yet, sorry.

**Comment by ulgens** [comment]
Hey again,

I finally tested it on my local. For both master and this branch, we have this error:

```
======================================================================
FAIL: module_pipelineNoisy_whole_test (tests_pipeline_caller.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ulgens/workspace/ITU-Turkish-NLP-Pipeline-Caller/tests_pipeline_caller.py", line 49, in module_pipelineNoisy_whole_test
    assert len(re.findall(r, response)) == 33
AssertionError
```
`len(re.findall(r, response)) ` from response is 29 and when i change 33 to 29, everything works fine for both branches.

**Comment by ferittuncer** [comment]
Looks like they changed their algorithm, we should update our test values accordingly. 

Also, as you can see, we have only some superficial smoke tests, feel free to improve them if you like.

How should we proceed with this pull requests?

**Comment by ferittuncer** [comment]
Nope, we get the same errors. Whatever works in a local run, doesn't work in the Travis environment. We must make sure the Travis environment works well too otherwise we can't review pull request.

Perhaps you can find something about this problem by checking Travis configurations and nosetests test suite configurations.

**Comment by ulgens** [comment]
"How should we proceed with this pull requests?"

It's always better to fix master, if sth. is broke in master, and other branches can be updated via rebase, but  fixing it here also works.

It also works on my local now, i'll investigate what breaks Travis soon.

**Comment by ulgens** [comment]
I'm closing this pull request. We found different problems on the way, i'll fix them and send one by one.

**Pull request closed without merging**
